//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Project12.rc에서 사용되고 있습니다.
//
#define IDB_MAP                         105
#define IDC_CURSOR1                     107
#define IDI_ICON1                       108
#define IDB_BULLET                      109
#define IDB_TITLE_BACKGROUND            110
#define IDB_TITLE_START                 111
#define IDB_TITLE_QUIT                  113
#define IDB_BOSS_B                      114
#define IDB_ENEMY_DRONI                 115
#define IDB_MODERN_BULLET               116
#define IDB_DRONI_BLINK                 118
#define IDB_RED_BULLET                  119
#define IDB_RED_BULLET_EX_1             120
#define IDB_RED_BULLET_EX_2             121
#define IDB_RED_BULLET_EX_3             122
#define IDB_RED_BULLET_EX_4             123
#define IDB_RED_BULLET_EX_5             124
#define IDB_RED_BULLET_EX_6             125
#define IDB_RED_BULLET_EX_7             126
#define IDB_RED_BULLET_EX_8             127
#define IDB_DRONI_IDLE_1                129
#define IDB_DRONI_IDLE_2                130
#define IDB_DRONI_IDLE_3                131
#define IDB_DRONI_IDLE_4                132
#define IDB_DRONI_IDLE_5                133
#define IDB_DRONI_IDLE_6                134
#define IDB_DRONI_IDLE_7                135
#define IDB_DRONI_DEATH_1               136
#define IDB_DRONI_DEATH_2               137
#define IDB_DRONI_DEATH_3               138
#define IDB_DRONI_DEATH_4               139
#define IDB_DRONI_DEATH_5               140
#define IDB_DRONI_DEATH_6               141
#define IDB_DRONI_DEATH_7               142
#define IDB_PLAYER                      154
#define IDB_PLAYER_MOVE_1               155
#define IDB_PLAYER_MOVE_2               156
#define IDB_PLAYER_MOVE_3               157
#define IDB_GUN_BEAN                    175
#define IDB_IMAGE_BEAN_GUN              176
#define IDB_ITEM_BEAN_GUN               177
#define IDB_FULL_HEART                  178
#define IDB_EMPTHY_HEART                179
#define IDB_CARPET_BRIDGE               180
#define IDB_CARPET_L                    181
#define IDB_CARPET_SIDE                 182
#define IDB_MIDDLE_COR_R_D              183
#define IDB_MIDDLE_COR_D_L              184
#define IDB_CARPET_S                    185
#define IDB_CARPET                      186
#define IDB_MIDDLE_D                    187
#define IDB_MIDDLE_L_D                  188
#define IDB_MIDDLE_L_U                  189
#define IDB_MIDDLE_D_R                  190
#define IDB_MIDDLE_R_U                  191
#define IDB_MIDDLE_R                    192
#define IDB_MIDDLE_L                    193
#define IDB_MIDDLE_U                    194
#define IDB_MIDDLE_WALL                 195
#define IDB_MIDDLE_WALL_S               196
#define IDB_PAUSE                       197
#define IDR_WAVE1                       198
#define IDB_BITMAP1                     199
#define IDB_TITLE_CONTINUE              200
#define IDB_CAT_PLAYER                  201
#define IDB_CAT_HURT_1                  202
#define IDB_CAT_HURT_2                  203
#define IDB_CAT_HURT_3                  204
#define IDB_CAT_HURT_4                  205
#define IDB_DEATH_1                     206
#define IDB_DEATH_2                     207
#define IDB_DEATH_3                     208
#define IDB_DEATH_4                     209
#define IDB_DEATH_5                     210
#define IDB_DEATH_6                     211
#define IDB_DEATH_7                     212
#define IDB_DEATH_8                     213
#define IDB_DEATH_9                     214
#define IDB_DEATH_10                    215
#define IDB_DEATH_11                    216
#define IDB_MULCHI                      217
#define IDB_MULCHI_WALK_1               218
#define IDB_MULCHI_WALK_2               219
#define IDB_MULCHI_HURT_1               220
#define IDB_MULCHI_HURT_2               221
#define IDB_MULCHI_HURT_3               222
#define IDB_YELLOW_BULLET               223
#define IDB_GUN_ASSERT                  224
#define IDB_IMAGE_ASSERT_GUN            225
#define IDB_ITEM_ASSERT_GUN             226
#define IDB_TITLE_1                     227
#define IDB_TITLE_2                     228
#define IDB_TITLE_3                     229
#define IDB_TITLE_4                     230
#define IDB_TITLE_5                     231
#define IDB_TITLE_6                     232
#define IDB_TITLE_7                     233
#define IDB_TITLE_8                     234
#define IDB_TITLE_9                     235
#define IDB_TITLE_10                    236
#define IDB_TITLE_11                    237
#define IDB_TITLE_12                    238
#define IDB_TITLE_13                    239
#define IDB_TITLE_14                    240
#define IDB_TITLE_15                    241
#define IDB_TITLE_16                    242
#define IDB_TITLE_17                    243
#define IDB_TITLE_18                    244
#define IDB_STAIR                       263
#define IDB_GUN_ICE                     264
#define IDB_IMAGE_ICE_GUN               265
#define IDB_ITEM_ICE_GUN                266
#define IDB_ICE_BULLET                  267
#define IDR_UPPER_CUT                   268
#define IDR_TITLE_OST                   269
#define IDB_INV_GUN                     270
#define IDB_INV_ITEM                    271
#define IDB_MIDEDUK                     272
#define IDB_MIDEDUK_MOVE_1              273
#define IDB_MIDEDUK_MOVE_2              274
#define IDB_MIDEDUK_HURT_1              275
#define IDB_MIDEDUK_HURT_2              276
#define IDB_MIDEDUK_HURT_3              277
#define IDB_EXPLOSION_1                 278
#define IDB_EXPLOSION_2                 279
#define IDB_EXPLOSION_3                 280
#define IDB_EXPLOSION_4                 281
#define IDB_EXPLOSION_5                 282
#define IDB_EXPLOSION_6                 283
#define IDB_EXPLOSION_7                 284
#define IDB_EXPLOSION_8                 285
#define IDB_NUP_HURT_1                  286
#define IDB_NUP_HURT_2                  287
#define IDB_NUP_HURT_3                  288
#define IDB_NUP_MOVE_1                  289
#define IDB_NUP_MOVE_2                  290
#define IDB_NUP_MOVE_3                  291
#define IDB_GAMEOVER                    292
#define IDB_RETRY                       293
#define IDB_WOOD_GUN                    294
#define IDB_WOOD_GUN_IMAGE              295
#define IDB_WOOD_BULLET                 296
#define IDB_ITEM_SPEED_RING             297
#define IDB_HEART_BAG                   298
#define IDB_BITMAP2                     299
#define IDB_NEW_ITEM                    299

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        300
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
